# Generated by Django 4.1.3 on 2023-03-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=100, verbose_name='组名称')),
            ],
            options={
                'db_table': 'myapp_group',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True, verbose_name='主机名')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('ipaddress', models.GenericIPAddressField(verbose_name='IP地址')),
                ('port', models.IntegerField(verbose_name='端口号')),
                ('auth_choice', models.CharField(blank=True, choices=[(1, '密码'), (2, '密钥')], max_length=30, verbose_name='认证类型')),
                ('auth_password', models.CharField(max_length=100, null=True, verbose_name='密码')),
                ('auth_key', models.CharField(max_length=100, null=True, verbose_name='密钥')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group', models.ManyToManyField(to='server.group')),
            ],
            options={
                'db_table': 'myapp_server',
            },
        ),
    ]
