# Generated by Django 4.1.3 on 2023-03-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serverdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='公网ip')),
                ('os_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='系统版本')),
                ('disk', models.CharField(blank=True, max_length=200, null=True, verbose_name='磁盘')),
                ('private_ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='内网ip')),
                ('machine_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='服务器类型')),
                ('cpu_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU核数')),
                ('hostname', models.CharField(blank=True, max_length=100, null=True, verbose_name='服务器主机名称')),
                ('cpu_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU信息')),
            ],
        ),
    ]
