# Generated by Django 4.1.3 on 2023-03-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_serverdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Serverdetails',
        ),
    ]
