# Generated by Django 4.1.3 on 2023-03-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_serverdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdetails',
            name='hostname',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='服务器主机名称'),
        ),
    ]
