# Generated by Django 4.1.3 on 2023-03-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_serverdetails_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='auth_choice',
            field=models.CharField(choices=[(1, '密码'), (2, '密钥')], max_length=30, verbose_name='认证类型'),
        ),
    ]
