# Generated by Django 4.1.3 on 2023-03-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_server_auth_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupname',
            field=models.CharField(max_length=100, unique=True, verbose_name='组名称'),
        ),
    ]
