# Generated by Django 4.1.3 on 2023-03-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_group_groupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdetails',
            name='memory',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='内存'),
        ),
    ]
