# Generated by Django 4.1.3 on 2023-03-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_serverdetails_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdetails',
            name='put_shelves_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='运行时间'),
        ),
    ]
