# Generated by Django 4.1.3 on 2023-04-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_serverdetails_put_shelves_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='auth_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='密钥'),
        ),
    ]
