# Generated by Django 4.1.3 on 2023-04-02 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdeploy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='app',
            table='myapp_app',
        ),
    ]
