# Generated by Django 4.1.3 on 2023-04-03 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdeploy', '0003_remove_app_app_logo_app_create_time_app_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='server',
        ),
    ]
