# Generated by Django 4.1.3 on 2023-04-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeploy', '0004_remove_app_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_package',
            field=models.URLField(verbose_name='应用包'),
        ),
    ]
