# Generated by Django 4.1.3 on 2023-04-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeploy', '0005_alter_app_app_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_package',
            field=models.URLField(max_length=100, verbose_name='应用包'),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_script',
            field=models.CharField(max_length=100, verbose_name='应用安装脚本'),
        ),
    ]
