# Generated by Django 3.0.1 on 2023-04-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeploy', '0007_alter_app_app_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_script',
            field=models.FileField(upload_to='knowledge_ase/', verbose_name='应用安装脚本'),
        ),
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
