# Generated by Django 4.1.3 on 2023-04-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdeploy', '0011_appdeploy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppDeploy',
        ),
    ]
