# Generated by Django 4.1.3 on 2023-04-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeploy', '0012_delete_appdeploy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDeploy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_hostanme', models.CharField(max_length=100, unique=True, verbose_name='已运行主机名')),
                ('app_public_ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='公网IP')),
                ('app_private_ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='内网IP')),
                ('app_server', models.ManyToManyField(to='appdeploy.app')),
            ],
            options={
                'db_table': 'myapp_runserver',
            },
        ),
    ]
