# Generated by Django 3.0.1 on 2023-04-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0002_alter_docdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docdb',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
